[package]
name = "par2rs"
version = "0.1.0"
edition = "2021"

[dependencies]
binrw = "*"
clap = "4.5.39"
rayon = "1.10.0"
md-5 = { version = "0.10", features = ["asm"] }
hex = "0.4.3"
crc32fast = "1.4.0"
log = "0.4"
env_logger = "0.11"
bytemuck = "1.24"
rustc-hash = "2.1"

[dev-dependencies]
# Test coverage and reporting tools
cargo-tarpaulin = "0.33"
# Temporary directory management for tests
tempfile = "3"
# Benchmarking framework
criterion = { version = "0.5", features = ["html_reports"] }

# Tarpaulin configuration
[package.metadata.tarpaulin]
# Exclude generated files and certain test directories from coverage
exclude = [
    "target/*",
    "scripts/*",
]
# Include all source files by default
include = [
    "src/*",
    "tests/*",
]
# Timeout for individual tests (in seconds)
timeout = 120
# Follow symbolic links
follow-links = true
# Count hits in tests 
count-hits = true
# Output timeout for individual tests
output-timeout = 60

[[bench]]
name = "repair_benchmark"
harness = false
